default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: progress_job_demo_dev
  username: root
  password:

test:
  <<: *default
  database: progress_job_demo_test
  username: root
  password:

production:
  <<: *default
  database: progress_job_demo
  username: ENV['MYSQL_USER']
  password: ENV['MYSQL_PASSWORD']
